### ISSUE TITLE
Is it possible to change the default colours for head/body/food/space?

### ISSUE THREAD

**Issue by MProx** [grantsrb/Gym-Snake#6]
It would be nice to be able to flatten the images to greyscale by averaging across the 3rd dimension in the observation array (i.e. reduce to a lower dimension), but currently the food colour becomes the same as the grid colour (85). 

I tried changing this:
grid_object.FOOD_COLOR = [0,0,0] # Color of food units

But it seemed to have no effect?

**Comment by Neqit** [comment]
@MProx
`/gym_snake/envs/snake/grid.py `
in rows 15-18 there are variables: BODY_COLOR, HEAD_COLOR, FOOD_COLOR and SPACE_COLOR. You can change the colors by editing their RGB values
